# Generated by Django 5.1.4 on 2026-06-06 15:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('featured_image', models.ImageField(upload_to='blog_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Crucial for SEO. Describe the image for search engines.', max_length=200)),
                ('image_caption', models.CharField(blank=True, help_text='Caption displayed below the image.', max_length=250)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Reading time in minutes.')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich text content.')),
                ('excerpt', models.TextField(help_text='Brief summary for the blog list page.', max_length=500)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description (max 160 chars)', max_length=160)),
                ('target_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (e.g. SEO, AI, Growth)', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blogs.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogpost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
