version: '3.8'

services:
  frontend_builder:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/app/dist

  backend:
    build:
      context: ./backend
    ports:
      # Map container 8000 to host 8000 (Ensure this doesn't conflict with other websites)
      - "8000:8000"
    volumes:
      - backend_media:/app/media
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=False
      - ALLOWED_HOSTS=toolnix.pro,www.toolnix.pro,127.0.0.1,localhost
      - CORS_ALLOWED_ORIGINS=https://toolnix.pro,https://www.toolnix.pro

volumes:
  frontend_dist:
  backend_media:
